name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage codecov

      - name: Auto-generate requirements from import
        run: |
          pip install pipreqs
          pipreqs src/ --force --savepath auto_requirements.txt
          pip install -r auto_requirements.txt

      # List file paths which are changed as a txt file
      - name: Get changed Python files
        run: |
          git fetch origin main
          git diff --name-only origin/main HEAD | grep '\.py$' > changed_files.txt

      # Select tests related to changed files
      - name: Select tests related to changed files
        run: python scripts/select_tests.py

      - name: Run selected tests and measure time
        run: |
          if [ -s .selected_tests ]; then
            echo "Running selected tests..."
            tests=$(cat .selected_tests | tr '\n' ' ')
          else
            echo "No related tests found, running all tests as fallback..."
            tests="tests/"
          fi

          start=$(date +%s)
          coverage run -m pytest --maxfail=1 --disable-warnings -q
          end=$(date +%s)
          echo "$((end - start))" > .runtime
          coverage xml
  
      - name: Evaluate test metrics (APFD, Coverage, etc.)
        run: python scripts/evaluate.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
