name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage codecov

      - name: Measure Execution Time
        run: |
          start=$(date +%s)
          coverage run -m pytest --maxfail=1 --disable-warnings -q
          end=$(date +%s)
          echo "$((end - start))" > .runtime
          coverage xml
  
      - name: Evaluate test metrics (APFD, Coverage, etc.)
        run: python scripts/evaluate.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
